<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>728e57a5-7dda-47cd-bae7-84d58951a6d1</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<ContainerImageName>default/eng-ai</ContainerImageName>
	<DockerfileTag>default/eng-ai:latest 149536470355.dkr.ecr.ap-southeast-1.amazonaws.com/default/eng-ai:latest</DockerfileTag>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.AspNetCore.Identity.Cognito" Version="4.0.0" />
    <PackageReference Include="Amazon.Extensions.CognitoAuthentication" Version="3.0.0" />
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="4.0.1.2" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Google.Apis.Auth.AspNetCore3" Version="1.70.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.16" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.5" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.Net.Http.Json" Version="9.0.4" />
  </ItemGroup>

</Project>
